name: 'Setup Node.js and pnpm'
description: 'Checkout, setup pnpm with cache, and install'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup pnpm
      uses: pnpm/action-setup@v6

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash