name: Scheduled or Manual Deploy

on:
  issues:
    types:
      - closed
      - deleted
  schedule:
    - cron: '0 15 31 12 *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-deploy:
    uses: ./.github/workflows/_reusable-deploy.yml
    secrets: inherit